services:
  - type: web
    name: afridigital-backend
    env: node
    buildCommand: cd SaaS/afridigital-frontend && npm install && npm run build && cd ../ && npm install
    startCommand: cd SaaS && node server.js
