services:
  # ===================== BACKEND API =====================
  - type: web
    name: afridigital-backend
    env: node
    rootDir: SaaS/afridigital-backend
    buildCommand: npm install
    startCommand: node server.js

  # ===================== FRONTEND STATIC =====================
  - type: static
    name: afridigital-frontend
    rootDir: SaaS/afridigital-frontend
    buildCommand: npm install && npm run build
    publishDir: dist
