services:
  - type: web
    name: afridigital-backend
    env: node

    buildCommand: |
      set -e
      npm install --prefix SaaS/afridigital-frontend
      npm run build --prefix SaaS/afridigital-frontend
      npm install --prefix SaaS/afridigital-backend

    startCommand: node SaaS/afridigital-backend/server.js
