// EVENT_SOURCED_KERNEL_ONLY
// AFRIKERNEL_RUNTIME_V1 (EVENT LOG → DAG → RENDER ONLY)
// AFRIKERNEL_V1_ACTIVE
// DETERMINISTIC_RENDER_PIPELINE_ENABLED
// AFRIKERNEL_V1_SINGLE_SOURCE_OF_TRUTH
// AFRIKERNEL_V1_SINGLE_RUNTIME_ACTIVE
// AFRIKERNEL_RENDER_PIPELINE_ACTIVE (NO DIRECT STATE, ONLY KERNEL PROJECTION)
// AFRIKERNEL_RUNTIME_ACTIVE (EVENT LOG → DAG → RENDER ONLY)
// AFRISYNC_V2_CLUSTER_REPLICATION_ACTIVE
// AFRIDIGITAL_CAUSAL_DAG_CONTROL_PLANE_V5
// AFRIDIGITAL_TRUE_DAG_SYSTEM_V4_ACTIVE
// AFRIDIGITAL_DAG_GRAPH_V3_FORCE_SIMULATION_ACTIVE
// AFRIDIGITAL_COMPRESSED_DAG_PIPELINE_ACTIVE
// AFRIDIGITAL_WS_DAG_COMPRESSION_PIPELINE_ACTIVE
// AFRIDIGITAL_EVENT_COMPRESSION_ENGINE_ACTIVE
// AFRIDIGITAL_EVENT_SOURCED_DAG_KERNEL_ACTIVE
// AFRIDIGITAL_CONTROL_PLANE_V2_ACTIVE
// AFRIDIGITAL_DAG_CONTROL_PLANE_ACTIVE
// AFRIDIGITAL_DAG_GRAPH_LAYER_ACTIVE
// AFRIDIGITAL_VISUAL_DAG_LAYER_ACTIVE
// AFRIDIGITAL_DAG_GRAPH_LAYER_ACTIVE
// AFRIDIGITAL_DAG_GRAPH_LAYER_ACTIVE
// DAG_GRAPH_LAYER_ACTIVE
import { useEffect, useState } from "react";
import { DagStore } from "./DAGRuntime";

export default function DagInspector() {
  const [events, setEvents] = useState(DagStore.events);

  useEffect(() => {
    const handler = (e) => {
      setEvents([...DagStore.events]);
    };
    window.addEventListener("DAG_EVENT", handler);
    return () => window.removeEventListener("DAG_EVENT", handler);
  }, []);

  return (
    <div style={{ padding: 10, color: "#0f0", fontFamily: "monospace" }}>
      <h3>DAG LIVE INSPECTOR</h3>
      <pre>{JSON.stringify(events.slice(-20), null, 2)}</pre>
    </div>
  );
}
