const AfriCCTVTrustSignalTypes = [
"COMPLETED_INSTALLATIONS",
"SYSTEM_UPTIME",
"INCIDENT_RESPONSE",
"CUSTOMER_RATINGS",
"DISPUTES",
"VERIFIED_TECHNICIANS",
"MAINTENANCE_SUCCESS"
];

export default AfriCCTVTrustSignalTypes;
