const AfriTickBenefitsRegistry = {
  BASIC:[
    "ACCOUNT_ACCESS"
  ],

  SILVER:[
    "ENHANCED_PROFILE",
    "BASIC_SUPPORT"
  ],

  GOLD:[
    "PROFILE_VISIBILITY_BOOST",
    "PRIORITY_SUPPORT",
    "SELLER_TOOLS"
  ],

  PREMIUM:[
    "ADVANCED_VISIBILITY",
    "AI_ASSISTANCE",
    "BUSINESS_ANALYTICS",
    "PREMIUM_SUPPORT",
    "MARKETPLACE_FEATURES"
  ],

  PLATINUM:[
    "OFFICIAL_PLATFORM_STATUS",
    "ADMIN_CONTROLS",
    "ECOSYSTEM_MANAGEMENT",
    "PLATFORM_ANALYTICS"
  ]
};

export default AfriTickBenefitsRegistry;
