#!/bin/bash

case "$1" in

view)
  bash afrifview.sh
  ;;

deploy)
  bash render-guard.sh && bash afripipeline-guard.sh && bash afrideploy.sh && \
  git add . && git commit -m "auto deploy: safe pipeline sync" && git push origin master
  ;;

build)
  bash afripipeline-guard.sh
  ;;

guard)
  bash render-guard.sh
  ;;

backup)
  bash afribk.sh
  ;;

restore)
  bash afribk-restore.sh
  ;;

*)
  echo "🧠 AfriMaster CLI"
  echo "Usage:"
  echo "  afri view"
  echo "  afri build"
  echo "  afri deploy"
  echo "  afri backup"
  echo "  afri restore"
  echo "  afri guard"
  ;;
esac
