// AFRIKERNEL_INGESTION_SINGLE_PATH_ENFORCED (AFRISYNC → DAGRuntime ONLY)
// AFRIKERNEL_PRODUCTION_MODE_LOCKED (NO ARCHITECTURE CHANGES ALLOWED)
// AFRIKERNEL_COLLAPSED_SINGLE_RUNTIME_ACTIVE
export const KERNEL_AUTH = {
  dag: 'DAGRuntime',
  renderer: 'RendererV2',
  physics: 'D3ForceRendererV2',
  ingest: 'AfriSyncCluster'
};
