import fs from "fs/promises";
import path from "path";
import AfriNucChainOperationDispatcher from "../execution/operations/AfriNucChainOperationDispatcher.js";

const AfriNucChainFilesystemRuntime = {

  async execute(input = {}) {

    const target = input.target || "src/core/afriai/nucchain/generated";
    const modules = input.modules || [];
    const files = input.files || [];
      const operations = input.operations || [];

    const created = [];
      const operationResults = [];
      for (const operation of operations) {
        operationResults.push(AfriNucChainOperationDispatcher.dispatch(operation));
      }

    if (files.length) {

      for (const file of files) {

        const fullPath = path.isAbsolute(file)
          ? file
          : path.resolve(process.cwd(), file);

        await fs.mkdir(
          path.dirname(fullPath),
          { recursive:true }
        );

        await fs.writeFile(
          fullPath,
          `// Generated by AfriNucChain\n// File: ${path.basename(fullPath)}\n`,
          "utf8"
        );

        created.push(fullPath);
      }

    } else {

        await fs.mkdir(target.endsWith(".js") ? path.dirname(target) : target,{recursive:true});

      for (const module of modules) {

          const file = target.endsWith(".js") ? target : path.join(target, `${module}.js`);

        await fs.writeFile(
          file,
          `// Generated by AfriNucChain\n// Module: ${module}\n`,
          "utf8"
        );

        created.push(file);
      }
    }

      return {
        status:"MATERIALIZED",
        created,
        count:created.length,
        operationResults,
        timestamp:Date.now()
      };
  }
};

export default AfriNucChainFilesystemRuntime;
