const AfriTickAPIContracts = [
  "GET_MEMBERSHIP_STATUS",
  "GET_TIER_BENEFITS",
  "CREATE_SUBSCRIPTION",
  "VERIFY_PAYMENT",
  "ACTIVATE_MEMBERSHIP",
  "CANCEL_SUBSCRIPTION",
  "GET_BILLING_HISTORY"
];

export default AfriTickAPIContracts;
